language: node_js

node_js:
  - 9
  - 8

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "citesteugen"
  api_key:
    secure: "7c67b11f-97b9-4722-b591-68d092710960"

cache:
  yarn: true
  directories:
    - node_modules
